spring:
  application:
    name: demo-toxiproxy-integration-tests
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:demoUser}
    password: ${DB_PASS:demoPass}
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/demo_db}
    hikari:
      minimum-idle: 2 # Minimum number of idle connections
      idle-timeout: 60000 # Idle timeout, e.g., 1 minute (in milliseconds)
      maximum-pool-size: ${DB_CONNECTIONS_NUMBER:10}  # Maximum number of connections in the pool
  jpa:
    #    generate-ddl: true
    database-platform: postgres
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      default-schema: public
    open-in-view: false
#    show-sql: true

scheduled:
  initial-delay: PT1S
  fixed-delay: PT10S

kafka:
  bootstrap-servers: ${BOOTSTRAP_SERVERS:http://localhost:9092}
  schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
  topics:
    order-events:
      name: ${ORDER_EVENTS_TOPIC_NAME:order-events}
