spring:
  application:
    name: demo-toxiproxy-integration-tests
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:demouser}
    password: ${DB_PASS:demoPass}
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/demo_db}
    hikari:
      minimum-idle: 2 # Minimum number of idle connections
      idle-timeout: 60000 # Idle timeout, e.g., 1 minute (in milliseconds)
      maximum-pool-size: ${DB_CONNECTIONS_NUMBER:10}  # Maximum number of connections in the pool
  jpa:
#    generate-ddl: true
    database-platform: postgres
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      default-schema: public
    open-in-view: false
#    show-sql: true

kafka:
  orders:
    topic:
      name: ${ORDERS_TOPIC_NAME:orders}
